name: ml1_flutter
description: ML-1 as a Flutter app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bonsai: ^1.0.1
  cupertino_icons: ^1.0.2
  dart_fire_midi:
    path: ../../dart_fire_midi
  flutter:
    sdk: flutter
  flutter_midi_command:
    path: ../../FlutterMidiCommand
  flutter_riverpod: ^1.0.3
  monochrome_draw: ^1.1.1
  oled_font_57: ^1.0.1
  tonic: ^0.2.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
